### ISSUE TITLE
Question about custom image dataset and corresponding camera views

### ISSUE THREAD

**Issue by colorful-liyu** [TAU-VAILab/Vox-E#5]
Thank you for your great work! I'm interested in 3D mesh editing. Assuming I have my own 3D  mesh （.obj） files and their related texture maps which need to be edited, how can I render it to get custom image sets and corresponding camera views to initiate the NERF? I have tried to render it with Blender and generate `transforms.json`， but Nerf training failed. I get a completely white image with nothing in it. 

Looking forward to your help!

**Comment by etaisella** [comment]
Thank you for your interest in Vox-E :)
[Here ](https://drive.google.com/file/d/1xtPCXKarbYTKv5TvzWFnwNg-S3rBmRUr/view?usp=sharing) is a link to the blender script we used to render the images and create the json files.

Before running the script we do the following:
1) Set the camera height and width to 800 pixels.
![image](https://github.com/TAU-VAILab/Vox-E/assets/74829220/ed8a516f-96cc-4ef9-88d6-70eef203ecc7)
2) Set the camera position and rotation like this:
![image](https://github.com/TAU-VAILab/Vox-E/assets/74829220/96198a37-7f80-4279-92e8-bee7d156d0b8)
3) Press 0 on the numpad to go into the camera view and scale the mesh (press s) so that it fits nicely into the frame:
![image](https://github.com/TAU-VAILab/Vox-E/assets/74829220/56bd7f1a-ac98-4063-a37e-d5f74f9a41ce)
4) In the script, set the output folders to whatever you want them to be:
![image](https://github.com/TAU-VAILab/Vox-E/assets/74829220/cae4d9d0-503a-48d8-bd07-dc0b02effd95)
![image](https://github.com/TAU-VAILab/Vox-E/assets/74829220/c66f17b6-d1b0-44c1-8262-01986a062aa0)

Hope this helps, feel free to open another issue if it doesn't :)

**Comment by colorful-liyu** [comment]
Thank you very much! It works!

**Comment by etaisella** [comment]
Great to hear!
Be sure to cite us if you find our work useful for your research :)

**Comment by colorful-liyu** [comment]
Yes, I will.
